// Copyright (c) 2025 Duplicati Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
using System.Text;

namespace MachineService.Common.Util;

/// <summary>
/// Helper class for performing the authentication handshake
/// </summary>
public static class AuthHandshake
{
    /// <summary>
    /// The three-part hash is created by concatenating the pre-shared key, and two nonces.
    /// </summary>
    /// <param name="preSharedKey">The pre-shared key</param>
    /// <param name="nonce1">A nonce, generated by the requester</param>
    /// <param name="nonce2">A nonce, generated by the responder</param>
    /// <returns>The three-part hash</returns>
    public static string CreateThreePartHash(string preSharedKey, byte[] nonce1, byte[] nonce2)
    {
        using (var ms = new MemoryStream())
        {
            ms.Write(Encoding.UTF8.GetBytes(preSharedKey));
            ms.Write(nonce1);
            ms.Write(nonce2);
            return Convert.ToBase64String(System.Security.Cryptography.SHA256.HashData(ms.ToArray()));
        }
    }
}
